# Generated by Django 3.2.23 on 2023-12-31 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='user_profile',
            new_name='userProfile',
        ),
    ]
