# Generated by Django 3.2.23 on 2023-12-31 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_rename_user_profile_profilefeeditem_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='userProfile',
            new_name='user_profile',
        ),
    ]
